name = "Cousins"
author = "fnnln"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3c26c8a099eddef363eb67853fb13e5e3c01f467f3df697e810c2f6b5c2106"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
