name = "Cousins"
author = "fnnln"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62cc99781b9091310a61d0e9ca201f88dc49e85b8d010dfd326d1b2cf5f87d40"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
