name = "Cousins"
author = "fnnln"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b5b6374450b7fa94a6490591c195efc0513ea59526934a3b985fa2513153ab1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
