name = "Cousins"
author = "fnnln"
version = "v0.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f8ac976d9d9767b8366bf99f4d9db995f454e54ecdcaff7e28fef9b4bb9c5c9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
