name = "Cousins"
author = "fnnln"
version = "v0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e18b9549a1ef82a2d2d9dc0c4ef9e0d5c0feddcef7a313922dd76e2848201880"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
