name = "Cousins"
author = "fnnln"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8300540e75243e7fd51dfaa196ae670564f5a216367d8f44625a03abbae7d29c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
