name = "Cousins"
author = "fnnln"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0be2f6c1c03e00fc314c9a2f547bf44dafff33bf9be52863e58df42671052b59"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
